def load_player(player_name):
    player = ...
    return player

def get_handedness(player):
    ...
    
def get_armslot(player):
    ...
    
def get_pitches(player):
    pitches = ...
    return pitches
    
def find_arsenal(pitches):
    ...
    
def find_stuff(pitches):
    ...
    
def find_location(pitches):
    ...
    
def find_tunnels(pitches):
    ...
    
def profile_player(player_name):
    ...